<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('produk')->insert([
    [
        'id_alat' => 'ALT001',
        'gambar' => 'vacuum-cleaner.jpg',
        'nama_alat' => 'Vacuum Cleaner',
        'jenis' => 'Elektronik',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Pusat',
        'harga' => 3500000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT002',
        'gambar' => 'robot-vacuum.jpg',
        'nama_alat' => 'Robot Vacuum',
        'jenis' => 'Elektronik',
        'kondisi' => 'Baru',
        'status' => 'Pre Order',
        'lokasi' => 'Gudang Tangerang',
        'harga' => 5800000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT003',
        'gambar' => 'floor-scrubber.jpg',
        'nama_alat' => 'Floor Scrubber',
        'jenis' => 'Mesin Pembersih',
        'kondisi' => 'Baru',
        'status' => 'Hampir Habis',
        'lokasi' => 'Gudang Pusat',
        'harga' => 8500000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT004',
        'gambar' => 'pressure-washer.jpg',
        'nama_alat' => 'High Pressure Washer',
        'jenis' => 'Mesin Pembersih',
        'kondisi' => 'Baru',
        'status' => 'Habis',
        'lokasi' => 'Gudang Bandung',
        'harga' => 4200000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT005',
        'gambar' => 'steam-cleaner.jpg',
        'nama_alat' => 'Steam Cleaner',
        'jenis' => 'Mesin Pembersih',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Pusat',
        'harga' => 2700000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT006',
        'gambar' => 'wet-dry-vacuum.jpg',
        'nama_alat' => 'Wet and Dry Vacuum',
        'jenis' => 'Elektronik',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Surabaya',
        'harga' => 2900000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT007',
        'gambar' => 'hand-dryer.jpg',
        'nama_alat' => 'Automatic Hand Dryer',
        'jenis' => 'Peralatan Toilet',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Jakarta',
        'harga' => 1850000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT008',
        'gambar' => 'soap-dispenser.jpg',
        'nama_alat' => 'Dispenser Sabun Otomatis',
        'jenis' => 'Peralatan Toilet',
        'kondisi' => 'Baru',
        'status' => 'Hampir Habis',
        'lokasi' => 'Gudang Jakarta',
        'harga' => 450000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT009',
        'gambar' => 'sensor-bin.jpg',
        'nama_alat' => 'Tempat Sampah Sensor',
        'jenis' => 'Tempat Sampah',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Pusat',
        'harga' => 650000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT010',
        'gambar' => 'air-purifier.jpg',
        'nama_alat' => 'Air Purifier',
        'jenis' => 'Elektronik',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Surabaya',
        'harga' => 2200000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT011',
        'gambar' => 'window-cleaner.jpg',
        'nama_alat' => 'Window Cleaner',
        'jenis' => 'Pembersih Kaca',
        'kondisi' => 'Baru',
        'status' => 'Habis',
        'lokasi' => 'Gudang Tangerang',
        'harga' => 320000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT012',
        'gambar' => 'microfiber-mop.jpg',
        'nama_alat' => 'Microfiber Mop',
        'jenis' => 'Pel',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Tangerang',
        'harga' => 180000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT013',
        'gambar' => 'flat-mop.jpg',
        'nama_alat' => 'Flat Mop',
        'jenis' => 'Pel',
        'kondisi' => 'Baru',
        'status' => 'Pre order',
        'lokasi' => 'Gudang Bandung',
        'harga' => 150000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT014',
        'gambar' => 'dust-mop.jpg',
        'nama_alat' => 'Dust Mop',
        'jenis' => 'Tersedia',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang B',
        'harga' => 170000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT015',
        'gambar' => 'lobby-dustpan.jpg',
        'nama_alat' => 'Lobby Dustpan',
        'jenis' => 'Peralatan',
        'kondisi' => 'Baru',
        'status' => 'Pre order',
        'lokasi' => 'Gudang Pusat',
        'harga' => 210000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT016',
        'gambar' => 'cleaning-trolley.jpg',
        'nama_alat' => 'Cleaning Trolley',
        'jenis' => 'Troli',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Jakarta',
        'harga' => 1450000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT017',
        'gambar' => 'chemical-sprayer.jpg',
        'nama_alat' => 'Chemical Sprayer',
        'jenis' => 'Semprotan',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Pusat',
        'harga' => 275000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT018',
        'gambar' => 'glass-wiper.jpg',
        'nama_alat' => 'Glass Wiper',
        'jenis' => 'Pembersih Kaca',
        'kondisi' => 'Baru',
        'status' => 'Habis',
        'lokasi' => 'Gudang Surabaya',
        'harga' => 95000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT019',
        'gambar' => 'floor-sign.jpg',
        'nama_alat' => 'Floor Sign',
        'jenis' => 'Perlengkapan',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Bandung',
        'harga' => 130000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id_alat' => 'ALT020',
        'gambar' => 'industrial-vacuum.jpg',
        'nama_alat' => 'Industrial Vacuum Cleaner',
        'jenis' => 'Elektronik',
        'kondisi' => 'Baru',
        'status' => 'Tersedia',
        'lokasi' => 'Gudang Jakarta',
        'harga' => 6900000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
]);
    }
}
